// Placeholder FirebaseOptions - PlatePilote FrontEnd.
//
// Until `flutterfire configure` runs against the real Firebase project,
// these placeholder options allow `lib/main.dart` to compile and run in
// dev without an UnsatisfiedLinkError or import error.
//
// Replace this file with the version generated by `flutterfire configure`
// (handled offline by a human, not by an agent).
//
// ignore_for_file: type=lint, prefer_const_constructors
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

const FirebaseOptions _placeholderAndroid = FirebaseOptions(
  apiKey: 'AIzaSy-placeholder-android',
  appId: '1:000000000000:android:0000000000000000',
  messagingSenderId: '000000000000',
  projectId: 'platepilote-dev',
);

const FirebaseOptions _placeholderIos = FirebaseOptions(
  apiKey: 'AIzaSy-placeholder-ios',
  appId: '1:000000000000:ios:0000000000000000',
  messagingSenderId: '000000000000',
  projectId: 'platepilote-dev',
);

const FirebaseOptions _placeholderWeb = FirebaseOptions(
  apiKey: 'AIzaSy-placeholder-web',
  appId: '1:000000000000:web:0000000000000000',
  messagingSenderId: '000000000000',
  projectId: 'platepilote-dev',
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholderWeb;
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return _placeholderIos;
      case TargetPlatform.android:
        return _placeholderAndroid;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return _placeholderWeb;
      case TargetPlatform.fuchsia:
        return _placeholderAndroid;
    }
  }
}
